### GET /
GET http://localhost:3000


###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "omeonu@gmail.com",
    "password": "12322244"
}


### route to login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "omeonu@gmail.com",
    "password": "12322244"
}

### Fetch all todos Get/ TODOS (PROTECTED

GET http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3ODA4NDA5LCJleHAiOjE3Mzc4OTQ4MDl9.lqB9KwNdljEG5j83csGAH8ozgeTWbg1RzTvvLrR1iko

### Create a new todo POST /TODOS (protected)

POST http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3ODA4NDA5LCJleHAiOjE3Mzc4OTQ4MDl9.lqB9KwNdljEG5j83csGAH8ozgeTWbg1RzTvvLrR1iko
Content-Type: application/json

{
    "task": "Finish coding the projects"
}

### Update a todo PUT / TODOS/:ID (protected route

PUT http://localhost:3000/todos/2?page=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3ODA4NDA5LCJleHAiOjE3Mzc4OTQ4MDl9.lqB9KwNdljEG5j83csGAH8ozgeTWbg1RzTvvLrR1iko
Content-Type: application/json

{
    "completed": 1
}

